volumes:
  rshop-pg:
  rshop-logs:
    
networks:
  default:
    name : 'rshop'

services:
  postgres:
    container_name: 'rshop-pg'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'rshop-pg:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: '1234'
      
  opensearch:
    container_name: 'rshop-os'
    image: 'opensearchproject/opensearch:2'
    ports:
      - '9200:9200'
      - '9600:9600'
    volumes:
      - 'rshop-logs:/usr/share/opensearch/data'
    environment:
      discovery.type: 'single-node'
      plugins.security.ssl.http.enabled: 'false'
      plugins.security.disabled: 'true'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'Strong__Pass123'
  
  opensearch-dashboards:
    container_name: 'rshop-osd'
    image: 'opensearchproject/opensearch-dashboards:latest'
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    depends_on:
      - opensearch
    
  